preventing docker release from running
Signed-off-by: hfuss <haydenfuss@gmail.com>

diff --git a/.github/workflows/docker_release.yml b/.github/workflows/docker_release.yml
--- a/.github/workflows/docker_release.yml
+++ b/.github/workflows/docker_release.yml
@@ -10,6 +10,12 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      - name: Filter Helm Releases
+        run: |
+          echo "Detected that GitHub release is for the Helm chart... aborting this build as a result."
+          exit 1
+        if: startsWith(github.ref, 'refs/tags/helm-v')
+
       - name: Build
         run: |
           docker build \
